### ISSUE TITLE
How widespread is this issue?

### ISSUE THREAD

**Issue by sandrodz** [mttrb/antipopd#4]
I wonder if this is Hardware issue, logic board, busted amp, speaker...
I refuse to believe this happens on every Mac.

Any insights?

I've MacBook Pro 2017 TB, pops after playing brief sounds like notifications.

**Comment by mttrb** [comment]
I don't personally have a need for `antipopd` anymore.  I believe there are some models of Mac that had an issue with a pop occurring when the sounds system was woken up.  However, I suspect the majority of users of `antipopd` are people with Hackintoshes.

What ever the reason, it is available if people want to use it :)

**Comment by adriel** [comment]
I use it with my MacBook Pro (15-inch, 2017), as I recently got an external USB Audio Interface (UMC22) which I now use as my audio out for my headset, but you can hear the pop right after each much track would end/start, would need to max out the audio on the Mac to hide it. But this removes the pop issue altogether, so thank you!

Also, I used to hear the pop with my Sennheiser monitoring headphones plugged directly into the Mac, but I forgot whether that was with this laptop or my old one. (I don't use those headphones much anymore)
